name: learnpy
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - plotly
  - bokeh
  - statsmodels
  - pyscaffold
  - Jupyter
  - pytest
  - sphinx
